version: '3.8'

services:
  stockadvisor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app/StockAdvisorApp
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - GOOGLE_GENAI_USE_VERTEXAI=FALSE
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}